---
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s8:
      addresses:
      - 192.168.0.2/28
      optional: false
      routes:
        - to: default
          via: 192.168.0.1
    enp0s19:
      addresses:
      - 192.168.56.12/24
      optional: false