---
- hosts: all
  become: true
  tasks:
    # Установка пакетов
    - name: Installing traceroute package on hosts
      apt:
        name: traceroute
        update_cache: yes
        state: present
      ignore_errors: true

    - name: Installing knockd package on centralServer and inetRouter
      apt:
        name: knockd
        state: present
      ignore_errors: true
      when: ansible_hostname == "centralServer" or ansible_hostname == "inetRouter"

    - name: Installing NGINX on centralServer
      apt:
        name: nginx
        state: present
      ignore_errors: true
      when: ansible_hostname == "centralServer"

    - name: Installing Knock Client on centralRouter
      apt:
        name: knockd
        state: present
      when: ansible_hostname == "centralRouter"

- hosts: inetRouter
  become: true
  tasks:
    - name: Installing iptables-persistent service
      apt:
        name: iptables-persistent
        state: present
      ignore_errors: true

    - name: Disabling ufw service
      systemd:
        name: ufw
        state: stopped
        enabled: no

    - name: Set up NAT
      template:
        src: rules_inetRouter.v4
        dest: /etc/iptables/rules.v4
        owner: root
        group: root
        mode: 0644

    - name: Configuring SSH service
      replace:
        path: /etc/ssh/sshd_config.d/60-cloudimg-settings.conf
        regexp: "PasswordAuthentication no"
        replace: "PasswordAuthentication yes"

    - name: Restarting SSH service
      systemd:
        name: sshd
        state: restarted
    
    - name: Copy setup_knockd.sh script to /home/vagrant/
      copy:
        src: templates/setup_knockd.sh
        dest: /home/vagrant/setup_knockd.sh
        owner: vagrant
        group: vagrant
        mode: '0755'    

- hosts: inetRouter2
  become: true
  tasks:
    - name: Installing iptables-persistent service
      apt:
        name: iptables-persistent
        state: present
      ignore_errors: true

    - name: Disabling ufw service
      systemd:
        name: ufw
        state: stopped
        enabled: no

    - name: Set up NAT
      template:
        src: rules_inetRouter2.v4
        dest: /etc/iptables/rules.v4
        owner: root
        group: root
        mode: 0644

- hosts: centralServer
  become: true
  tasks:
    - name: Change nginx port to 8080
      replace:
        path: /etc/nginx/sites-available/default
        regexp: '    listen [::]:80 default_server;'
        replace: '    listen [::]:8080 default_server;'
      notify: restart nginx

    - name: Change nginx port to 8080 (IPv4)
      replace:
        path: /etc/nginx/sites-available/default
        regexp: '    listen 80 default_server;'
        replace: '    listen 8080 default_server;'
      notify: restart nginx

    - name: Start nginx
      systemd:
        name: nginx
        enabled: true
        state: started

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted

- hosts: all
  become: true
  tasks:
    # Конфигурирование маршрутов и настроек интерфейсов
    - name: Set up forward packages across routers
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
      when: "'routers' in group_names"

    - name: disable default route
      template: 
        src: "templates/00-installer-config.yaml"
        dest: "/etc/netplan/00-installer-config.yaml"
        owner: root
        group: root
        mode: 0644
      when:
        - ansible_hostname != "inetRouter" 
        - ansible_hostname != "inetRouter2"

    - name: Route configuring on hosts
      template:
        src: "templates/50-vagrant_{{ansible_hostname}}.yaml"
        dest: /etc/netplan/50-vagrant.yaml
        owner: root
        group: root
        mode: 0644

    - name: remove cloud-init netplan configuration
      file:
        path: /etc/netplan/50-cloud-init.yaml
        state: absent

    - name: restart all hosts
      reboot:
        reboot_timeout: 600
